apiVersion: v1
kind: Namespace
metadata:
  name: operators
  labels:
    app: otus-homework
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rofl
  namespace: operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rofl-operator-role
  namespace: default
  labels:
    app: otus-homework
rules:
  - verbs:
      - create
      - delete
    apiGroups:
      - "*"
    resources:
      - services
      - persistentvolumeclaims
  - verbs:
      - create
    apiGroups:
      - ""
    resources:
      - events
  - verbs:
      - "*"
    apiGroups:
      - apps
    resources:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rofl-operator-role
  namespace: default
subjects:
  - kind: ServiceAccount
    name: rofl
    namespace: operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rofl-operator-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rofl-operator-manage-pv-role
  labels:
    app: otus-homework
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
    apiGroups:
      - ""
    resources:
      - persistentvolumes
  - verbs:
      - "*"
    apiGroups:
      - otus.homework
    resources:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rofl-operator-manage-pv-rb
subjects:
  - kind: ServiceAccount
    name: rofl
    namespace: operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rofl-operator-manage-pv-role
