apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-application
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  # Add labels to your application object.
  labels:
    name: demo-application
spec:
  # The project the application belongs to.
  project: otus

  # Source of the application manifests
  source:
    repoURL: https://github.com/Kuber-2024-08OTUS/ilyangru_repo.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: kubernetes-gitops  # For Helm, this refers to the chart version.
    path: kubernetes-gitops/demo-application  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.

  # Destination cluster and namespace to deploy the application
  destination:
    # cluster API URL
    # server: https://kubernetes.default.svc
    # or cluster name
    name: in-cluster
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: homework
