apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp
  labels:
    app: deployment-demo
    version: v1
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: deployment-demo
  template:
    metadata:
      name: dp
      labels:
        app: deployment-demo
        managed-by: homework
    spec:
      initContainers:
        - name: init-webserver
          image: busybox
          command:
            - wget
            - "-O"
            - "/init/index.html"
            - "https://www.cncf.io/about/who-we-are/"
          volumeMounts:
            - mountPath: /init/
              name: workdir
      containers:
        - name: webserver
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - name: www
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /homework
              name: workdir
            - mountPath: /usr/share/nginx/html
              name: workdir
              readOnly: true
            - mountPath: /etc/nginx/conf.d
              name: nginx-config-volume
              readOnly: true
          workingDir: /homework
          lifecycle:
            preStop:
              exec:
                command: [ "rm /homework/index.html" ]
          readinessProbe:
            httpGet:
              port: www
              path: /index.html
        - name: nginx-exporter
          image: 'nginx/nginx-prometheus-exporter'
          args:
            - '--nginx.scrape-uri=http://localhost/status'
          ports:
            - containerPort: 9113
              name: metrics
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: workdir
          emptyDir: {}
        - name: nginx-config-volume
          configMap:
            name: nginx-config
