apiVersion: v1
kind: Service
metadata:
  name: deployment-demo-metrics
  namespace: homework
  labels:
    app: deployment-demo-service
    version: v1
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
spec:
  selector:
    app: deployment-demo
  ports:
    - protocol: TCP
      port: 9113
      targetPort: metrics
      name: nginx-metrics
  type: ClusterIP
  