apiVersion: v1
kind: Service
metadata:
  name: deployment-demo-metrics
  labels:
    app: deployment-demo-service
    #version: v1
#  annotations:
#    prometheus.io/scrape: "true"
#    prometheus.io/port: "9113"
spec:
  selector:
    app: deployment-demo
  ports:
    - protocol: TCP
      port: 9113
      targetPort: 9113
      name: nginx-metrics
  type: ClusterIP
  