apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: homework
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-homework
rules:
#- apiGroups:
#    - v1
#  verbs:
#    - get
#    - list
#    - watch
#  resources:
#    - endpoints
#  resourceNames:
#    - metrics-server
- nonResourceURLs:
    - "/metrics"
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-homework-crb
subjects:
  - kind: ServiceAccount
    name: monitoring
    namespace: homework
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-homework
