apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-homework
  namespace: homework
subjects:
  - kind: ServiceAccount
    name: cd
    namespace: homework
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: cd-kubeconfig-sa-token
  namespace: homework
  annotations:
    kubernetes.io/service-account.name: cd
type: kubernetes.io/service-account-token
# Сгенерировать для ServiceAccount cd токен с временем действия 1 день и сохранить его в файл token:
# kubectl create token cd --namespace=homework --duration=86400s > token
#
