{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quest-one.serviceAccountName" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
    {{- include "quest-one.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "quest-one.serviceAccountName" . }}
  labels:
    {{- include "quest-one.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- nonResourceURLs:
    - "/metrics"
  verbs:
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "quest-one.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "quest-one.serviceAccountName" . }}
    namespace: {{ .Values.nameSpace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "quest-one.serviceAccountName" . }}
{{- end }}
