apiVersion: v2
name: quest-one
version: 0.1.0
type: application
appVersion: "latest"
description: Simple deployment from kubernetes-security homework
icon: "https://upload.wikimedia.org/wikipedia/commons/1/19/Otus-logo.png"
dependencies:
  - name: logging-operator
    version: "4.2.1"
    repository: "https://kube-logging.github.io/helm-charts"
